### PR TITLE
Adding Sort option 

### PR DESCRIPTION
**Pull request by sylvain-d**
Answer to issue #46

Add a new property to Search function to support sort.
leboncoin offers two sort option, by date or by price, ascending or descending.

With  : 
`.setSort({sort_by:"date",sort_order:"asc"})`
add at the end of bodyParams
`"sort_by":"date","sort_order":"asc"}`

Properties `sort_by` and `sort_order` are set to null if Search.sort is null or the properties are wrong.
Even null the request works.

### CODE REVIEW

**Comment by tdurieux** [comment]
There is a conflict with the master can you fix it?

Thank you

**Comment by sylvain-d** [comment]
Resolved.
I rewrite my comment in README.md

Should be fine

**Comment by sylvain-d** [comment]
:( forget to modify the tests.
Going back to code

**Comment by tdurieux** [comment]
Thanks a lot for your PR, I will publish a new version on npm

**Comment by sylvain-d** [comment]
Le travail de base est un vrai plus pour moi. 
C'est avec plaisir.

**Comment by mishka81** [comment]
thats' nice, thanks for your reactivity !

**Pull request merged**
